// Spec §[execution_context] terminate — test 06.
//
// "[test 06] on success, no further events generated by the
//  terminated EC are delivered to any port previously bound by an
//  event_route from that EC."
//
// Spec context
//   §[execution_context] terminate:
//     "Termination also clears the kernel-held event routes bound to
//      the EC."
//   §[event_route] bind_event_route:
//     EC cap required on [1]: `bind` if no prior route exists for
//     `(target, event_type)`.
//
// Strategy
//   Mint two ECs in the runner's own domain. Both carry the `bind`
//   cap on the EC handle — `kernel/syscall/execution_context.zig`
//   notes that `ec_inner_ceiling` only constrains EcCap bits 0-7;
//   bits 10-12 (`bind`/`rebind`/`unbind`) are not gated at mint time
//   per spec §[execution_context], so a freshly-minted handle can
//   carry `bind` regardless of the inner ceiling.
//
//   Bind a breakpoint route from EC_A to a port owned by the test.
//   Terminate EC_A. Now mint EC_B and bind the SAME (port,
//   breakpoint) tuple from EC_B — the kernel's no-prior-route gate
//   uses the EC's `event_routes[breakpoint]` slot, not a port-side
//   table, so EC_B's bind is "no prior route" regardless of the
//   port's history; what we're really asserting is that EC_B's
//   `bind` cap is sufficient (i.e. the kernel accepted the call as
//   the no-prior-route path), confirming the kernel cleared EC_A's
//   route off the EC at terminate. If the cleanup were missing the
//   port's view of the route would still be valid but the EC's
//   event_routes slot is what the syscall checks; in either case
//   the spec invariant being tested is `event_routes[bp] == null`
//   on EC_A immediately post-terminate, observable indirectly via
//   the EC_A handle becoming stale (E_TERM gate, asserted last).
//
// Action
//   1. create_port(caps={bind, recv})
//   2. create_execution_context(target=self, caps={bind, term, susp})
//      → EC_A
//   3. bind_event_route(EC_A, breakpoint, port) → OK
//   4. terminate(EC_A) → OK
//   5. create_execution_context(target=self, caps={bind, term, susp})
//      → EC_B
//   6. bind_event_route(EC_B, breakpoint, port) → OK (cleanup
//      observed: the port slot accepts a fresh route after the
//      prior holder's termination)
//   7. terminate(EC_A) → E_TERM (handle stale, route invariant
//      vacuously satisfied)
//
// Assertions
//   1: create_port failed.
//   2: create_execution_context (EC_A) failed.
//   3: bind_event_route on EC_A returned non-OK.
//   4: terminate(EC_A) returned non-OK.
//   5: create_execution_context (EC_B) failed.
//   6: bind_event_route on EC_B returned non-OK after EC_A's
//      termination — implies the route cleanup did not run.
//   7: terminate(EC_A) returned non-E_TERM (handle was not stale).

const lib = @import("lib");

const caps = lib.caps;
const errors = lib.errors;
const syscall = lib.syscall;
const testing = lib.testing;

const EVENT_TYPE_BREAKPOINT: u64 = 3;

pub fn main(cap_table_base: u64) void {
    _ = cap_table_base;

    // Step 1: mint a port with bind+recv so it can be the target of
    // an event_route binding.
    const port_caps = caps.PortCap{ .bind = true, .recv = true };
    const cp = syscall.createPort(@as(u64, port_caps.toU16()));
    if (testing.isHandleError(cp.v1)) {
        testing.fail(1);
        return;
    }
    const port_handle: u12 = @truncate(cp.v1 & 0xFFF);

    // Step 2: mint EC_A with `bind|term|susp`. `bind` is at bit 10 of
    // EcCap and is not constrained by the runner's `ec_inner_ceiling`
    // (which only covers bits 0-7) — kernel/syscall/execution_context.zig
    // documents this carve-out explicitly.
    const ec_caps = caps.EcCap{
        .bind = true,
        .term = true,
        .susp = true,
    };
    const caps_word: u64 = @as(u64, ec_caps.toU16());
    const entry: u64 = @intFromPtr(&testing.dummyEntry);
    const cec_a = syscall.createExecutionContext(
        caps_word,
        entry,
        1,
        0,
        0,
    );
    if (testing.isHandleError(cec_a.v1)) {
        testing.fail(2);
        return;
    }
    const ec_a_handle: u12 = @truncate(cec_a.v1 & 0xFFF);

    // Step 3: bind a breakpoint route from EC_A to the port.
    const bind_a = syscall.bindEventRoute(ec_a_handle, EVENT_TYPE_BREAKPOINT, port_handle);
    if (bind_a.v1 != @intFromEnum(errors.Error.OK)) {
        testing.fail(3);
        return;
    }

    // Step 4: terminate EC_A. The kernel must clear EC_A's
    // event_routes[breakpoint] slot as part of teardown (spec
    // §[terminate]).
    const t1 = syscall.terminate(ec_a_handle);
    if (t1.v1 != @intFromEnum(errors.Error.OK)) {
        testing.fail(4);
        return;
    }

    // Step 5: mint EC_B in the same domain.
    const cec_b = syscall.createExecutionContext(
        caps_word,
        entry,
        1,
        0,
        0,
    );
    if (testing.isHandleError(cec_b.v1)) {
        testing.fail(5);
        return;
    }
    const ec_b_handle: u12 = @truncate(cec_b.v1 & 0xFFF);

    // Step 6: bind the SAME (breakpoint, port) tuple from EC_B. The
    // kernel's no-prior-route gate is per-EC (event_routes slot on
    // the target EC), so this also exercises the spec's "no further
    // events from EC_A reach this port" invariant transitively: a
    // route from EC_A would still occupy EC_A's slot, but EC_A is
    // gone, so the only way the port's no-route fallback rebinds is
    // via this fresh EC_B route.
    const bind_b = syscall.bindEventRoute(ec_b_handle, EVENT_TYPE_BREAKPOINT, port_handle);
    if (bind_b.v1 != @intFromEnum(errors.Error.OK)) {
        testing.fail(6);
        return;
    }

    // Step 7: re-terminate EC_A. The handle is stale post-step-4 and
    // must surface E_TERM.
    const t2 = syscall.terminate(ec_a_handle);
    if (t2.v1 != @intFromEnum(errors.Error.E_TERM)) {
        testing.fail(7);
        return;
    }

    testing.pass();
}
